[package]

name = "zookeeper"
version = "0.1.0"
authors = ["Nandor Kracser <bonifaido@gmail.com>"]
license = "MIT"
homepage = "https://github.com/bonifaido/rust-zookeeper"
repository = "https://github.com/bonifaido/rust-zookeeper"
description = "A minimal ZooKeeper client, work in progress"
readme = "README.md"

[dependencies]
enum_primitive = "0.0.2"
num = "0.1.24"
byteorder = "0.3.9"
schedule_recv = "0.0.1"

[features]
unstable = []
