[package]
name = "zookeeper"
version = "0.6.0"
authors = ["Nandor Kracser <bonifaido@gmail.com>"]
license = "MIT"
homepage = "https://github.com/bonifaido/rust-zookeeper"
repository = "https://github.com/bonifaido/rust-zookeeper"
documentation = "http://bonifaido.github.io/rust-zookeeper"
description = "A minimal ZooKeeper client"
readme = "README.md"
keywords = ["zk", "zookeeper", "distributed", "coordination"]

[dependencies]
byteorder = "1.2"
bytes = "0.4"
lazy_static = "0.1"
log = "0.4"
mio = "0.6"
mio-extras = "2"
snowflake = "1.0.0"
zookeeper_derive = { path = "zookeeper-derive", version = "0.3.0" }

[dev-dependencies]
env_logger = "0.5"

[features]
unstable = []

[[test]]
name = "test"
path = "tests/test.rs"
