[package]
name = "zookeeper"
version = "0.2.2"
authors = ["Nandor Kracser <bonifaido@gmail.com>"]
license = "MIT"
homepage = "https://github.com/bonifaido/rust-zookeeper"
repository = "https://github.com/bonifaido/rust-zookeeper"
documentation = "http://bonifaido.github.io/rust-zookeeper"
description = "A minimal ZooKeeper client"
readme = "README.md"
keywords = ["zk", "zookeeper", "distributed", "coordination"]

[dependencies]
byteorder = "1.0"
enum_primitive = "0.1"
lazy_static = "0.2"
log = "0.3"
mio = "0.6"
num = "0.1"
snowflake = "1.2"
bytes = "0.4"

[dev-dependencies]
env_logger = "0.3"

# [features]
# unstable = []

[[test]]
name = "test"
path = "tests/test.rs"
